module.exports = `(() => { try {
 const d=document.querySelector('gorak-frame-designer');
 const root=()=>d.shadowRoot;
 const get=key=>root().querySelector('[aria-label="'+key+'"]');
 const clickMenu=label=>Array.from(document.querySelectorAll('.menubar button')).find(b=>b.textContent.startsWith(label)).click();
 const pointer=(target,type,x,y,options={})=>target.dispatchEvent(new PointerEvent(type,{bubbles:true,button:0,pointerId:7,clientX:x,clientY:y,...options}));
 if(!d||root().querySelectorAll('[data-field]').length!==3)throw Error('Missing fixture fields');
 if(root().querySelector('nav').getAttribute('aria-label')!=='Field palette'||document.querySelector('.notice')||root().querySelector('[data-action="source"]'))throw Error('Editor layout failed');
 for(const [id,name] of [['12','ControlButton'],['13','BarField'],['15','RectangleShape'],['19','PaletteField'],['20','PopupButton'],['22','TabFolder']])if(!root().querySelector('[data-tool="'+id+'"]').getAttribute('aria-label').includes(name))throw Error('Incorrect native palette mapping: '+id);
 const entry=d.document.fields.find(f=>f.kind==='entryfield').id;
 d.selectField(entry);
 if(d.selectedFieldId!==entry||get('datatype').value!=='varchar(40)')throw Error('Selection failed');
 // Read-only is an opt-in component mode, and can be reversed at runtime.
 if(d.readOnly!==false)throw Error('Editing must remain the component default');
 const viewerSource=d.document.source.text, viewerMetadata=d.document.metadata?.text;
 let viewerEdits=0;const countViewerEdit=()=>viewerEdits++;
 d.addEventListener('edit-intent',countViewerEdit);
 d.readOnly=true;
 if(getComputedStyle(get('bgcolor')).appearance!=='none')throw Error('Viewer property dropdown arrow visible');
 if(!get('width').disabled||root().querySelector('.handle')||getComputedStyle(root().querySelector('.palette')).display!=='none')throw Error('Read-only editing controls visible');
 get('width').value='9999';get('width').dispatchEvent(new Event('change'));
 d.deleteSelection();d.groupSelection('flexibleform');d.ungroupSelection();
 d.dispatchEvent(new KeyboardEvent('keydown',{key:'Delete',bubbles:true}));
 const viewerField=root().querySelector('[data-field="'+entry+'"]');
 pointer(viewerField,'pointerdown',100,100);pointer(window,'pointermove',160,160);pointer(window,'pointerup',160,160);
 if(root().querySelector('.preview'))throw Error('Read-only drag preview');
 const zoomBefore=d.zoom;get('Zoom in').click();if(d.zoom<=zoomBefore)throw Error('Viewer zoom failed');get('Actual size').click();
 let navigation;d.addEventListener('source-navigation',e=>navigation=e.detail,{once:true});d.requestSourceNavigation(entry);
 if(!navigation?.range)throw Error('Viewer navigation failed');
 const fieldActions=[];d.addEventListener('field-action',e=>fieldActions.push(e.detail));
 const openFieldMenu=()=>root().querySelector('[data-field="'+entry+'"]').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:100,clientY:100}));
 openFieldMenu();
 let fieldMenu=root().querySelector('[role="menu"]');
 if(!fieldMenu||d.selectedFieldId!==entry)throw Error('Field context menu missing');
 fieldMenu.querySelector('button').click();
 openFieldMenu();fieldMenu=root().querySelector('[role="menu"]');
 fieldMenu.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));
 if(root().activeElement.textContent!=='Find All References')throw Error('Field menu keyboard navigation failed');
 root().activeElement.click();
 if(fieldActions.map(a=>a.action).join(',')!=='definition,references')throw Error('Field actions missing');
 for(const action of fieldActions)if(action.uri!==d.document.uri||action.version!==d.document.version||action.fieldId!==entry||action.name!==d.document.fields.find(f=>f.id===entry).name||!d.document.source.text.slice(action.range.start,action.range.end).startsWith('<entryfield'))throw Error('Field action identity mismatch: '+JSON.stringify(action));
 openFieldMenu();root().querySelector('[role="menu"]').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));
 if(root().querySelector('[role="menu"]'))throw Error('Field menu Escape failed');

 d.selectFrame();if(!get('windowwidth').disabled)throw Error('Companion editable in viewer');
 get('windowwidth').value='9999';get('windowwidth').dispatchEvent(new Event('change'));
 if(viewerEdits||d.document.source.text!==viewerSource||d.document.metadata?.text!==viewerMetadata)throw Error('Viewer emitted an edit');
 d.removeEventListener('edit-intent',countViewerEdit);
 d.readOnly=false;d.selectField(entry);
 if(get('width').disabled||!root().querySelector('.handle')||getComputedStyle(root().querySelector('.palette')).display==='none')throw Error('Editing did not resume');
 get('width').value='2600';get('width').dispatchEvent(new Event('change'));
 if(get('width').value!=='2600'||!document.title.includes('*'))throw Error('In-memory property edit failed');
 clickMenu('Undo');if(get('width').value!=='2400')throw Error('Undo failed');
 clickMenu('Redo');if(get('width').value!=='2600')throw Error('Redo failed');clickMenu('Undo');
 const button=d.document.fields.find(f=>f.kind==='buttonfield').id;d.selectField(button);
 if(!get('bgcolor').selectedOptions[0].textContent.includes('Native default'))throw Error('Native omission label missing');
 if(root().querySelectorAll('.properties button').length)throw Error('Unexpected reset buttons');
 get('bgcolor').value='6';get('bgcolor').dispatchEvent(new Event('change'));
 if(!d.document.source.text.includes('bgcolor="6"'))throw Error('Inherited property not materialized');clickMenu('Undo');
 get('bgcolor').value='6';get('bgcolor').dispatchEvent(new Event('change'));get('bgcolor').value='__inherit__';get('bgcolor').dispatchEvent(new Event('change'));
 if(d.document.source.text.includes('bgcolor="6"')||get('bgcolor').value!=='__inherit__')throw Error('Default reset failed');clickMenu('Undo');clickMenu('Undo');
 d.selectField(entry);
 pointer(root().querySelector('[data-field="'+button+'"]'),'pointerdown',120,120,{shiftKey:true});
 if(d.selectedFieldIds.length!==2)throw Error('Shift selection failed');
 const multiBefore=d.document.source.text;
 d.dispatchEvent(new KeyboardEvent('keydown',{key:'Delete',bubbles:true}));
 if(d.document.fields.length!==1)throw Error('Multi delete failed');clickMenu('Undo');
 if(d.document.source.text!==multiBefore)throw Error('Delete undo lost source');
 const frameBounds=root().querySelector('.canvas').getBoundingClientRect();
 pointer(root().querySelector('.surface'),'pointerdown',frameBounds.left,frameBounds.top);
 pointer(window,'pointermove',frameBounds.left+d.document.width,frameBounds.top+d.document.height);pointer(window,'pointerup',frameBounds.left+d.document.width,frameBounds.top+d.document.height);
 if(d.selectedFieldIds.length!==3)throw Error('Marquee selection failed');
 const groupBefore=d.document.source.text;
 d.groupSelection('flexibleform');
 const groupField=d.document.fields.find(f=>f.kind==='flexibleform');
 if(!groupField||d.document.fields.length!==4)throw Error('Grouping failed: '+document.querySelector('.status').textContent);
 const nested=d.document.fields.find(f=>f.parentId===groupField.id);
 pointer(root().querySelector('[data-field="'+nested.id+'"]'),'pointerdown',120,120,{ctrlKey:true});
 if(d.selectedFieldId!==groupField.id)throw Error('Parent selection failed');
 d.ungroupSelection();if(d.document.fields.length!==3)throw Error('Ungroup failed');clickMenu('Undo');clickMenu('Undo');
 if(d.document.source.text!==groupBefore)throw Error('Grouping undo lost source');
 d.selectFields([entry,button]);d.groupSelection('stackfield');
 const stack=d.document.fields.find(f=>f.kind==='stackfield'), stackChildren=d.document.fields.filter(f=>f.parentId===stack.id), moved=stackChildren[1], stackBefore=d.document.source.text;
 d.selectField(moved.id);
 const childBounds=root().querySelector('[data-field="'+moved.id+'"]').getBoundingClientRect();
 pointer(root().querySelector('[data-field="'+moved.id+'"]'),'pointerdown',childBounds.left+10,childBounds.top+10);
 pointer(window,'pointermove',childBounds.left+10,childBounds.top-150);pointer(window,'pointerup',childBounds.left+10,childBounds.top-150);
 if(d.document.fields.filter(f=>f.parentId===stack.id)[0].name!==moved.name)throw Error('Stack drag reorder failed');
 clickMenu('Undo');if(d.document.source.text!==stackBefore)throw Error('Stack gesture was not one undoable edit');clickMenu('Undo');
 if(d.document.source.text!==groupBefore)throw Error('Stack grouping undo lost source');
 const menu=document.querySelector('.menubar details');menu.open=true;
 d.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,composed:true}));if(menu.open)throw Error('Menu dismissal failed');
 d.selectFrame();if(root().querySelector('.objectname').value==='WINDOW')throw Error('Frame name missing');
 pointer(root().querySelector('.surface'),'pointerdown',300,300);
 pointer(window,'pointerup',300,300);
 if(d.selectedFieldId!==undefined||!get('windowwidth'))throw Error('Window selection failed');
 const before=d.document.width;
 pointer(root().querySelector('[data-resize="se"]'),'pointerdown',300,300);
 pointer(window,'pointermove',330,320);pointer(window,'pointerup',330,320);
 if(d.document.width<=before)throw Error('Frame resize failed');clickMenu('Undo');
 root().querySelector('[data-action="in"]').click();if(d.zoom!==1.25)throw Error('Zoom failed');root().querySelector('[data-action="reset"]').click();
 root().querySelector('[data-tool="1"]').click();
 const bounds=root().querySelector('.canvas').getBoundingClientRect();
 pointer(root().querySelector('.surface'),'pointerdown',bounds.left+300,bounds.top+230);pointer(window,'pointerup',bounds.left+300,bounds.top+230);
 if(d.document.fields.length!==4||!d.document.source.text.includes('name="field1"'))throw Error('Palette creation failed: '+d.document.fields.length+' '+document.querySelector('.status').textContent+' '+d.document.source.text);
 clickMenu('Undo');if(d.document.fields.length!==3)throw Error('Creation undo failed');
 clickMenu('Redo');if(d.document.fields.length!==4)throw Error('Creation redo failed');clickMenu('Undo');d.selectFrame();
 const tabOriginal=d.document, sample=tabOriginal.fields[0], tabSource=tabOriginal.source.text;
 const bitmap={width:1,height:1,rgba:new Uint8ClampedArray([255,0,0,255])};
 d.document={...tabOriginal,uri:'neutral-tabs',fields:[
  {...sample,id:'folder',kind:'tabfolder',parentId:undefined,pageScopes:undefined},
  {...sample,id:'tab0',kind:'tabfield',parentId:'folder',tabTarget:{folderId:'folder',index:0},bitmap},
  {...sample,id:'tab1',kind:'tabfield',parentId:'folder',tabTarget:{folderId:'folder',index:1}},
  {...sample,id:'page-a',pageScopes:[{folderId:'folder',index:0}]},
  {...sample,id:'page-b',pageScopes:[{folderId:'folder',index:1}]}]};
 if(!root().querySelector('[data-field="page-a"]')||root().querySelector('[data-field="page-b"]'))throw Error('Initial tab visibility failed');
 const tabCanvas=root().querySelector('[data-field="tab0"] canvas');if(!tabCanvas||tabCanvas.getContext('2d').getImageData(0,0,1,1).data[0]!==255)throw Error('Bitmap preview failed');
 pointer(root().querySelector('[data-field="tab1"]'),'pointerdown',100,100);
 if(!root().querySelector('[data-field="page-b"]')||root().querySelector('[data-field="page-a"]')||d.document.source.text!==tabSource)throw Error('Tab switch modified source or failed visibility');
 d.selectField('page-a');if(!root().querySelector('[data-field="page-a"]'))throw Error('Source selection did not reveal hidden page');
 d.document={...tabOriginal,uri:'neutral-radio',fields:[{...sample,id:'radio',kind:'radiofield',properties:{...sample.properties,defaultstring:'',curenumindex:'2',orientation:'2'},choices:[{label:'First',value:'a'},{label:'Second',value:'b'}]}]};
 const radioDots=root().querySelector('[data-field="radio"]').querySelectorAll('span');
 if(!Array.from(radioDots).some(dot=>dot.style.background.includes('radial-gradient')&&dot.parentElement.textContent==='Second'))throw Error('Radio current choice lost to empty default');
 d.document=tabOriginal;d.selectFrame();
 const original=d.document,start=performance.now(); d.document={...original,fields:Array.from({length:10000},(_,i)=>({...original.fields[0],id:'large-'+i,x:(i%100)*30,y:Math.floor(i/100)*30}))}; const rendered=root().querySelectorAll('[data-field]').length;if(rendered>1000||root().querySelector('.selection').options.length>1002)throw Error('Large frame DOM is unbounded');const ms=Math.round(performance.now()-start);d.document=original;return 'PASS: palette, inspector, inherited edits, window selection, resize, dirty state, undo/redo and zoom; 10,000-field view '+ms+' ms, '+rendered+' rendered fields';
} catch(error) { return "FAIL: "+error.stack; } })()`;
